{
  "type": "issue",
  "issue": {
    "id": 2611936910,
    "node_id": "I_kwDOABII586brv6O",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31151",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31151/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31151/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31151/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/31151",
    "number": 31151,
    "state": "open",
    "state_reason": null,
    "title": "ci: intermittent issue in rpc_misc.py   node0 stderr terminate called after throwing an instance of 'kj::ExceptionImpl' [15:12:14.943]   what():  mp/proxy.cpp:242: disconnected: write(m_post_fd, &buffer, 1): Broken pipe [15:12:14.943] stack: 657ed083 657ed86e f7ac7d20 f7713156 f77a7e07 ",
    "body": "https://cirrus-ci.com/task/5442110629871616?logs=ci#L3430\r\n\r\n```\r\n[15:12:14.943]  node0 2024-10-24T15:12:14.578291Z [shutoff] [src/logging/timer.h:58] [Log] [bench] FlushStateToDisk: write block and undo data to disk started \r\n[15:12:14.943]  node0 2024-10-24T15:12:14.578357Z [shutoff] [src/logging/timer.h:58] [Log] [bench] FlushStateToDisk: write block and undo data to disk completed (0.06ms) \r\n[15:12:14.943]  node0 2024-10-24T15:12:14.578365Z [shutoff] [src/logging/timer.h:58] [Log] [bench] FlushStateToDisk: write block index to disk started \r\n[15:12:14.943]  node0 2024-10-24T15:12:14.578381Z [shutoff] [src/logging/timer.h:58] [Log] [bench] FlushStateToDisk: write block index to disk completed (0.01ms) \r\n[15:12:14.943]  node0 2024-10-24T15:12:14.578390Z [shutoff] [src/logging/timer.h:58] [Log] [bench] FlushStateToDisk: write coins cache to disk (0 coins, 262kB) started \r\n[15:12:14.943]  node0 2024-10-24T15:12:14.578406Z [shutoff] [src/txdb.cpp:146] [BatchWrite] [coindb] Writing final batch of 0.00 MiB \r\n[15:12:14.943]  node0 2024-10-24T15:12:14.578614Z [shutoff] [src/txdb.cpp:148] [BatchWrite] [coindb] Committed 0 changed transaction outputs (out of 0) to coin database... \r\n[15:12:14.943]  node0 2024-10-24T15:12:14.578640Z [shutoff] [src/logging/timer.h:58] [Log] [bench] FlushStateToDisk: write coins cache to disk (0 coins, 262kB) completed (0.24ms) \r\n[15:12:14.943]  node0 2024-10-24T15:12:14.578654Z [shutoff] [src/validationinterface.cpp:245] [ChainStateFlushed] [validation] Enqueuing ChainStateFlushed: block hash=08088a81df63d1c115663bb817c7ce81057d3e9e57dc706c85e4f3878390e828 \r\n[15:12:14.943]  node0 2024-10-24T15:12:14.585972Z [shutoff] [src/init.cpp:398] [Shutdown] Shutdown: done \r\n[15:12:14.943]  node0 2024-10-24T15:12:14.586061Z [capnp-loop] [src/ipc/capnp/protocol.cpp:35] [IpcLogFn] [ipc] {bitcoin-node-21814/b-capnp-loop-21841} EventLoop::loop done, cancelling event listeners. \r\n[15:12:14.943]  node0 2024-10-24T15:12:14.586078Z [capnp-loop] [src/ipc/capnp/protocol.cpp:35] [IpcLogFn] [ipc] {bitcoin-node-21814/b-capnp-loop-21841} EventLoop::loop bye. \r\n[15:12:14.943]  test  2024-10-24T15:12:14.621000Z TestFramework (ERROR): Assertion failed \r\n[15:12:14.943]                                    Traceback (most recent call last):\r\n[15:12:14.943]                                      File \"/ci_container_base/test/functional/test_framework/test_framework.py\", line 132, in main\r\n[15:12:14.943]                                        self.run_test()\r\n[15:12:14.943]                                      File \"/ci_container_base/ci/scratch/build-i686-pc-linux-gnu/test/functional/rpc_misc.py\", line 83, in run_test\r\n[15:12:14.943]                                        self.restart_node(0, [\"-txindex\", \"-blockfilterindex\", \"-coinstatsindex\"])\r\n[15:12:14.943]                                      File \"/ci_container_base/test/functional/test_framework/test_framework.py\", line 595, in restart_node\r\n[15:12:14.943]                                        self.stop_node(i)\r\n[15:12:14.943]                                      File \"/ci_container_base/test/functional/test_framework/test_framework.py\", line 581, in stop_node\r\n[15:12:14.943]                                        self.nodes[i].stop_node(expected_stderr, wait=wait)\r\n[15:12:14.943]                                      File \"/ci_container_base/test/functional/test_framework/test_node.py\", line 410, in stop_node\r\n[15:12:14.943]                                        self.wait_until_stopped(expected_stderr=expected_stderr)\r\n[15:12:14.943]                                      File \"/ci_container_base/test/functional/test_framework/test_node.py\", line 445, in wait_until_stopped\r\n[15:12:14.943]                                        self.wait_until(lambda: self.is_node_stopped(**kwargs), timeout=timeout)\r\n[15:12:14.943]                                      File \"/ci_container_base/test/functional/test_framework/test_node.py\", line 843, in wait_until\r\n[15:12:14.943]                                        return wait_until_helper_internal(test_function, timeout=timeout, timeout_factor=self.timeout_factor)\r\n[15:12:14.943]                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n[15:12:14.943]                                      File \"/ci_container_base/test/functional/test_framework/util.py\", line 292, in wait_until_helper_internal\r\n[15:12:14.943]                                        if predicate():\r\n[15:12:14.943]                                           ^^^^^^^^^^^\r\n[15:12:14.943]                                      File \"/ci_container_base/test/functional/test_framework/test_node.py\", line 445, in <lambda>\r\n[15:12:14.943]                                        self.wait_until(lambda: self.is_node_stopped(**kwargs), timeout=timeout)\r\n[15:12:14.943]                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n[15:12:14.943]                                      File \"/ci_container_base/test/functional/test_framework/test_node.py\", line 430, in is_node_stopped\r\n[15:12:14.943]                                        raise AssertionError(\"Unexpected stderr {} != {}\".format(stderr, expected_stderr))\r\n[15:12:14.943]                                    AssertionError: Unexpected stderr terminate called after throwing an instance of 'kj::ExceptionImpl'\r\n[15:12:14.943]                                      what():  mp/proxy.cpp:242: disconnected: write(m_post_fd, &buffer, 1): Broken pipe\r\n[15:12:14.943]                                    stack: 657ed083 657ed86e f7ac7d20 f7713156 f77a7e07 !=\r\n[15:12:14.943]  test  2024-10-24T15:12:14.623000Z TestFramework (DEBUG): Closing down network thread \r\n[15:12:14.943]  test  2024-10-24T15:12:14.673000Z TestFramework (INFO): Stopping nodes \r\n[15:12:14.943]  test  2024-10-24T15:12:14.673000Z TestFramework.node0 (DEBUG): Stopping node \r\n[15:12:14.943] \r\n[15:12:14.943]  node0 stderr terminate called after throwing an instance of 'kj::ExceptionImpl'\r\n[15:12:14.943]   what():  mp/proxy.cpp:242: disconnected: write(m_post_fd, &buffer, 1): Broken pipe\r\n[15:12:14.943] stack: 657ed083 657ed86e f7ac7d20 f7713156 f77a7e07 ",
    "user": {
      "login": "maflcko",
      "id": 6399679,
      "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/maflcko",
      "html_url": "https://github.com/maflcko",
      "followers_url": "https://api.github.com/users/maflcko/followers",
      "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
      "organizations_url": "https://api.github.com/users/maflcko/orgs",
      "repos_url": "https://api.github.com/users/maflcko/repos",
      "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/maflcko/received_events",
      "type": "User",
      "site_admin": false,
      "patch_url": null
    },
    "labels": [
      {
        "id": 2260068353,
        "node_id": "MDU6TGFiZWwyMjYwMDY4MzUz",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/interfaces",
        "name": "interfaces",
        "description": "",
        "color": "83c9fc",
        "default": false
      },
      {
        "id": 5334691551,
        "node_id": "LA_kwDOABII588AAAABPfju3w",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/CI%20failed",
        "name": "CI failed",
        "description": "",
        "color": "cccccc",
        "default": false
      }
    ],
    "assignees": [],
    "author_association": "MEMBER",
    "locked": false,
    "comments": 4,
    "created_at": "2024-10-24T15:27:34Z",
    "updated_at": "2025-01-22T21:38:52Z"
  },
  "events": [
    {
      "event": "labeled",
      "id": 14853912416,
      "node_id": "LE_lADOABII586brv6OzwAAAAN1XLdg",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/14853912416",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-10-24T15:27:58Z",
      "label": {
        "name": "interfaces",
        "color": "83c9fc"
      }
    },
    {
      "event": "labeled",
      "id": 14853912432,
      "node_id": "LE_lADOABII586brv6OzwAAAAN1XLdw",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/14853912432",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-10-24T15:27:58Z",
      "label": {
        "name": "CI failed",
        "color": "cccccc"
      }
    },
    {
      "event": "commented",
      "id": 2435611527,
      "node_id": "IC_kwDOABII586RLHuH",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2435611527",
      "actor": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-10-24T15:29:02Z",
      "updated_at": "2024-10-24T15:29:02Z",
      "author_association": "MEMBER",
      "body": "cc @ryanofsky ",
      "user": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/31151#issuecomment-2435611527",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31151"
    },
    {
      "event": "mentioned",
      "id": 14853932319,
      "node_id": "MEE_lADOABII586brv6OzwAAAAN1XQUf",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/14853932319",
      "actor": {
        "login": "ryanofsky",
        "id": 7133040,
        "node_id": "MDQ6VXNlcjcxMzMwNDA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7133040?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ryanofsky",
        "html_url": "https://github.com/ryanofsky",
        "followers_url": "https://api.github.com/users/ryanofsky/followers",
        "following_url": "https://api.github.com/users/ryanofsky/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/ryanofsky/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/ryanofsky/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/ryanofsky/subscriptions",
        "organizations_url": "https://api.github.com/users/ryanofsky/orgs",
        "repos_url": "https://api.github.com/users/ryanofsky/repos",
        "events_url": "https://api.github.com/users/ryanofsky/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/ryanofsky/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-10-24T15:29:05Z"
    },
    {
      "event": "subscribed",
      "id": 14853932347,
      "node_id": "SE_lADOABII586brv6OzwAAAAN1XQU7",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/14853932347",
      "actor": {
        "login": "ryanofsky",
        "id": 7133040,
        "node_id": "MDQ6VXNlcjcxMzMwNDA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7133040?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ryanofsky",
        "html_url": "https://github.com/ryanofsky",
        "followers_url": "https://api.github.com/users/ryanofsky/followers",
        "following_url": "https://api.github.com/users/ryanofsky/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/ryanofsky/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/ryanofsky/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/ryanofsky/subscriptions",
        "organizations_url": "https://api.github.com/users/ryanofsky/orgs",
        "repos_url": "https://api.github.com/users/ryanofsky/repos",
        "events_url": "https://api.github.com/users/ryanofsky/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/ryanofsky/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-10-24T15:29:05Z"
    },
    {
      "event": "commented",
      "id": 2444170080,
      "node_id": "IC_kwDOABII586RrxNg",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2444170080",
      "actor": {
        "login": "ryanofsky",
        "id": 7133040,
        "node_id": "MDQ6VXNlcjcxMzMwNDA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7133040?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ryanofsky",
        "html_url": "https://github.com/ryanofsky",
        "followers_url": "https://api.github.com/users/ryanofsky/followers",
        "following_url": "https://api.github.com/users/ryanofsky/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/ryanofsky/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/ryanofsky/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/ryanofsky/subscriptions",
        "organizations_url": "https://api.github.com/users/ryanofsky/orgs",
        "repos_url": "https://api.github.com/users/ryanofsky/repos",
        "events_url": "https://api.github.com/users/ryanofsky/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/ryanofsky/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-10-29T13:05:55Z",
      "updated_at": "2024-10-29T13:05:55Z",
      "author_association": "CONTRIBUTOR",
      "body": "Assuming this is a new error, it is possible this is caused by #31105 which was merged a week ago and changed some parts of IPC shutdown sequence.\r\n\r\nIt seems this failure here is happening because some code is trying to use the IPC event loop after it is closed. Specifically some code is calling the `mp::EventLoop::removeClient` which fails writing to the event loop's local pipe at https://github.com/chaincodelabs/libmultiprocess/blob/abe254b9734f2e2b220d1456de195532d6e6ac1e/src/mp/proxy.cpp#L242",
      "user": {
        "login": "ryanofsky",
        "id": 7133040,
        "node_id": "MDQ6VXNlcjcxMzMwNDA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7133040?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ryanofsky",
        "html_url": "https://github.com/ryanofsky",
        "followers_url": "https://api.github.com/users/ryanofsky/followers",
        "following_url": "https://api.github.com/users/ryanofsky/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/ryanofsky/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/ryanofsky/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/ryanofsky/subscriptions",
        "organizations_url": "https://api.github.com/users/ryanofsky/orgs",
        "repos_url": "https://api.github.com/users/ryanofsky/repos",
        "events_url": "https://api.github.com/users/ryanofsky/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/ryanofsky/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/31151#issuecomment-2444170080",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31151"
    },
    {
      "event": "commented",
      "id": 2444255035,
      "node_id": "IC_kwDOABII586RsF87",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2444255035",
      "actor": {
        "login": "ryanofsky",
        "id": 7133040,
        "node_id": "MDQ6VXNlcjcxMzMwNDA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7133040?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ryanofsky",
        "html_url": "https://github.com/ryanofsky",
        "followers_url": "https://api.github.com/users/ryanofsky/followers",
        "following_url": "https://api.github.com/users/ryanofsky/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/ryanofsky/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/ryanofsky/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/ryanofsky/subscriptions",
        "organizations_url": "https://api.github.com/users/ryanofsky/orgs",
        "repos_url": "https://api.github.com/users/ryanofsky/repos",
        "events_url": "https://api.github.com/users/ryanofsky/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/ryanofsky/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-10-29T13:35:51Z",
      "updated_at": "2024-10-29T13:35:51Z",
      "author_association": "CONTRIBUTOR",
      "body": "Looking more closely at changes in #31105, I don't see anything that directly relates to this code, so it seems possible this is an older bug or a different bug. Looking up the \"Broken pipe\" error, it also seems like that can only be triggered if something is closing the `EventLoop::m_wait_fd` file descriptor before the `write(m_post_fd, ...)` call happens. But I don't see a code path where that would happen. May need to reproduce locally to debug. Would be curious to know if this happens more.",
      "user": {
        "login": "ryanofsky",
        "id": 7133040,
        "node_id": "MDQ6VXNlcjcxMzMwNDA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7133040?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ryanofsky",
        "html_url": "https://github.com/ryanofsky",
        "followers_url": "https://api.github.com/users/ryanofsky/followers",
        "following_url": "https://api.github.com/users/ryanofsky/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/ryanofsky/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/ryanofsky/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/ryanofsky/subscriptions",
        "organizations_url": "https://api.github.com/users/ryanofsky/orgs",
        "repos_url": "https://api.github.com/users/ryanofsky/repos",
        "events_url": "https://api.github.com/users/ryanofsky/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/ryanofsky/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/31151#issuecomment-2444255035",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31151"
    },
    {
      "event": "subscribed",
      "id": 16025728678,
      "node_id": "SE_lADOABII586brv6OzwAAAAO7NTam",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/16025728678",
      "actor": {
        "login": "Sjors",
        "id": 10217,
        "node_id": "MDQ6VXNlcjEwMjE3",
        "avatar_url": "https://avatars.githubusercontent.com/u/10217?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Sjors",
        "html_url": "https://github.com/Sjors",
        "followers_url": "https://api.github.com/users/Sjors/followers",
        "following_url": "https://api.github.com/users/Sjors/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/Sjors/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/Sjors/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/Sjors/subscriptions",
        "organizations_url": "https://api.github.com/users/Sjors/orgs",
        "repos_url": "https://api.github.com/users/Sjors/repos",
        "events_url": "https://api.github.com/users/Sjors/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/Sjors/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2025-01-22T09:08:22Z"
    },
    {
      "event": "commented",
      "id": 2608324576,
      "node_id": "IC_kwDOABII586bd9_g",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/2608324576",
      "actor": {
        "login": "ryanofsky",
        "id": 7133040,
        "node_id": "MDQ6VXNlcjcxMzMwNDA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7133040?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ryanofsky",
        "html_url": "https://github.com/ryanofsky",
        "followers_url": "https://api.github.com/users/ryanofsky/followers",
        "following_url": "https://api.github.com/users/ryanofsky/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/ryanofsky/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/ryanofsky/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/ryanofsky/subscriptions",
        "organizations_url": "https://api.github.com/users/ryanofsky/orgs",
        "repos_url": "https://api.github.com/users/ryanofsky/repos",
        "events_url": "https://api.github.com/users/ryanofsky/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/ryanofsky/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2025-01-22T21:38:51Z",
      "updated_at": "2025-01-22T21:38:51Z",
      "author_association": "CONTRIBUTOR",
      "body": "I've been looking into this issue since it was reported again https://github.com/chaincodelabs/libmultiprocess/issues/128#issuecomment-2604033275 and was able to get it to happen by removing other code in rpc_misc.py, so it is only calling `node.echoipc` and `self.stop_node(0)`, and then running the test in a loop. If I do that I tend to see the crash after 20-30 minutes of looping the test. I also tried implementing a change to dump IPC debug logs from the child `bitcoin-node` processs that is spawned during the test, but unfortunately this change made the problem disappear when the test was run in a loop overnight, so I don't have great information about what is leading up and causing the child process to crash,\n\n<details><summary>diff</summary>\n<p>\n\n```diff\n@@ -32,6 +33,9 @@ namespace capnp {\n namespace {\n void IpcLogFn(bool raise, std::string message)\n {\n+    std::ofstream f(\"/tmp/echoclient.txt\", std::ios::app);\n+    f << message << std::endl;\n+    f.close();\n     LogDebug(BCLog::IPC, \"%s\\n\", message);\n     if (raise) throw Exception(message);\n }\n```\n</p>\n</details>\n\nThe one useful thing I could get was a stack trace from the core dump, which looks like:\n\n<details><summary>stack trace</summary>\n<p>\n\n```c++\n#+begin_src c++\n#0  0x00007f96ad7b2a9c in __pthread_kill_implementation () from /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6\n#1  0x00007f96ad760576 in raise () from /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6\n#2  0x00007f96ad748935 in abort () from /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6\n#3  0x00007f96adaacc2b in __gnu_cxx::__verbose_terminate_handler() [clone .cold] () from /nix/store/ybjcla5bhj8g1y84998pn4a2drfxybkv-gcc-13.3.0-lib/lib/libstdc++.so.6\n#4  0x00007f96adabc20a in __cxxabiv1::__terminate(void (*)()) () from /nix/store/ybjcla5bhj8g1y84998pn4a2drfxybkv-gcc-13.3.0-lib/lib/libstdc++.so.6\n#5  0x00007f96adabc275 in std::terminate() () from /nix/store/ybjcla5bhj8g1y84998pn4a2drfxybkv-gcc-13.3.0-lib/lib/libstdc++.so.6\n#6  0x00007f96adabc4c7 in __cxa_throw () from /nix/store/ybjcla5bhj8g1y84998pn4a2drfxybkv-gcc-13.3.0-lib/lib/libstdc++.so.6\n#7  0x000055d3346d6275 in kj::ExceptionCallback::RootExceptionCallback::onFatalException(kj::Exception&&) ()\n#8  0x000055d3357661f5 in kj::throwFatalException(kj::Exception&&, unsigned int) ()\n#9  0x000055d335761de3 in kj::_::Debug::Fault::fatal() ()\n#10 0x000055d3355edbe9 in mp::EventLoop::removeClient(std::unique_lock<std::mutex>&)::$_0::operator()() const (this=<optimized out>) at mp/src/mp/proxy.cpp:244\n#11 mp::Unlock<std::unique_lock<std::mutex>, mp::EventLoop::removeClient(std::unique_lock<std::mutex>&)::$_0>(std::unique_lock<std::mutex>&, mp::EventLoop::removeClient(std::unique_lock<std::mutex>&)::$_0&&) (lock=..., callback=...) at mp/include/mp/util.h:157\n#12 mp::EventLoop::removeClient (this=this@entry=0x55d365fc2528, lock=...) at mp/src/mp/proxy.cpp:242\n#13 0x000055d3355f0033 in mp::EventLoop::startAsyncThread(std::unique_lock<std::mutex>&)::$_0::operator()() const (this=<optimized out>) at mp/src/mp/proxy.cpp:262\n#14 std::__invoke_impl<void, mp::EventLoop::startAsyncThread(std::unique_lock<std::mutex>&)::$_0>(std::__invoke_other, mp::EventLoop::startAsyncThread(std::unique_lock<std::mutex>&)::$_0&&) (__f=...)\n    at /nix/store/4krab2h0hd4wvxxmscxrw21pl77j4i7j-gcc-13.3.0/include/c++/13.3.0/bits/invoke.h:61\n#15 std::__invoke<mp::EventLoop::startAsyncThread(std::unique_lock<std::mutex>&)::$_0>(mp::EventLoop::startAsyncThread(std::unique_lock<std::mutex>&)::$_0&&) (__fn=...)\n    at /nix/store/4krab2h0hd4wvxxmscxrw21pl77j4i7j-gcc-13.3.0/include/c++/13.3.0/bits/invoke.h:96\n#16 std::thread::_Invoker<std::tuple<mp::EventLoop::startAsyncThread(std::unique_lock<std::mutex>&)::$_0> >::_M_invoke<0ul> (this=<optimized out>)\n    at /nix/store/4krab2h0hd4wvxxmscxrw21pl77j4i7j-gcc-13.3.0/include/c++/13.3.0/bits/std_thread.h:292\n#17 std::thread::_Invoker<std::tuple<mp::EventLoop::startAsyncThread(std::unique_lock<std::mutex>&)::$_0> >::operator() (this=<optimized out>)\n    at /nix/store/4krab2h0hd4wvxxmscxrw21pl77j4i7j-gcc-13.3.0/include/c++/13.3.0/bits/std_thread.h:299\n#18 std::thread::_State_impl<std::thread::_Invoker<std::tuple<mp::EventLoop::startAsyncThread(std::unique_lock<std::mutex>&)::$_0> > >::_M_run (this=<optimized out>)\n    at /nix/store/4krab2h0hd4wvxxmscxrw21pl77j4i7j-gcc-13.3.0/include/c++/13.3.0/bits/std_thread.h:244\n#19 0x00007f96adae86d3 in execute_native_thread_routine () from /nix/store/ybjcla5bhj8g1y84998pn4a2drfxybkv-gcc-13.3.0-lib/lib/libstdc++.so.6\n#20 0x00007f96ad7b0d02 in start_thread () from /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6\n#21 0x00007f96ad8303ac in __clone3 () from /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6\n#+end_src\n```\n</p>\n</details>\n\nThe stack trace shows the crash is happening in `EventLoop::startAsyncThread` when it is calling `EventLoop::removeClient`:\n\nhttps://github.com/chaincodelabs/libmultiprocess/blob/3b2617b3e59f55ae3501c82a62c87f393077779f/src/mp/proxy.cpp#L260\n\nwhich is failing when it tries to write to `EventLoop::m_post_fd`:\n\nhttps://github.com/chaincodelabs/libmultiprocess/blob/3b2617b3e59f55ae3501c82a62c87f393077779f/src/mp/proxy.cpp#L242\n\nbut as mentioned earlier https://github.com/bitcoin/bitcoin/issues/31151#issuecomment-2444255035, it's not clear why that write would ever fail because the pipe should be open for reading at that point. Since I couldn't easily add more log prints, I tried looking at surrounding code for reference counting-bugs, to see if there was any shutdown sequence that might lead to stopping the event loop early and closing the pipe, but I couldn't find anything. Looking at the EventLoop thread I did see some cases where locks for `EventLoop::m_mutex` are missing, so I will try to add those and see if that helps. If it doesn't and I might try to add delays different places to see if I can get the bug to happen more reliably. I also need to try building libmultiprocess code with -fsanitize=thread (regardless of this bug), since there might be other issues it could catch.",
      "user": {
        "login": "ryanofsky",
        "id": 7133040,
        "node_id": "MDQ6VXNlcjcxMzMwNDA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7133040?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ryanofsky",
        "html_url": "https://github.com/ryanofsky",
        "followers_url": "https://api.github.com/users/ryanofsky/followers",
        "following_url": "https://api.github.com/users/ryanofsky/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/ryanofsky/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/ryanofsky/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/ryanofsky/subscriptions",
        "organizations_url": "https://api.github.com/users/ryanofsky/orgs",
        "repos_url": "https://api.github.com/users/ryanofsky/repos",
        "events_url": "https://api.github.com/users/ryanofsky/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/ryanofsky/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/31151#issuecomment-2608324576",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31151"
    }
  ]
}