{
  "type": "issue",
  "issue": {
    "id": 3016360691,
    "node_id": "I_kwDOABII586zygLz",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/32334",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/32334/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/32334/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/32334/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/32334",
    "number": 32334,
    "state": "open",
    "state_reason": null,
    "title": "intermittent issue in feature_bip68_sequence.py: sequence_value = utxos[j][\"confirmations\"]                                                          IndexError: list index out of range",
    "body": "https://cirrus-ci.com/task/5337593233014784?logs=ci#L3671\n\n```\n test  2025-04-23T20:13:04.883000Z TestFramework (ERROR): Unexpected exception caught during testing \n                                   Traceback (most recent call last):\n                                     File \"/ci_container_base/test/functional/test_framework/test_framework.py\", line 182, in main\n                                       self.run_test()\n                                     File \"/ci_container_base/ci/scratch/build-i686-pc-linux-gnu/test/functional/feature_bip68_sequence.py\", line 70, in run_test\n                                       self.test_sequence_lock_confirmed_inputs()\n                                     File \"/ci_container_base/ci/scratch/build-i686-pc-linux-gnu/test/functional/feature_bip68_sequence.py\", line 173, in test_sequence_lock_confirmed_inputs\n                                       sequence_value = utxos[j][\"confirmations\"]\n                                                        ~~~~~^^^\n                                   IndexError: list index out of range",
    "user": {
      "login": "maflcko",
      "id": 6399679,
      "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/maflcko",
      "html_url": "https://github.com/maflcko",
      "followers_url": "https://api.github.com/users/maflcko/followers",
      "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
      "organizations_url": "https://api.github.com/users/maflcko/orgs",
      "repos_url": "https://api.github.com/users/maflcko/repos",
      "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/maflcko/received_events",
      "type": "User",
      "site_admin": false,
      "patch_url": null
    },
    "labels": [
      {
        "id": 5334691551,
        "node_id": "LA_kwDOABII588AAAABPfju3w",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/CI%20failed",
        "name": "CI failed",
        "description": "",
        "color": "cccccc",
        "default": false
      }
    ],
    "assignees": [],
    "author_association": "MEMBER",
    "locked": false,
    "comments": 0,
    "created_at": "2025-04-24T07:48:41Z",
    "updated_at": "2025-04-24T07:48:47Z"
  },
  "events": [
    {
      "event": "labeled",
      "id": 17385149214,
      "node_id": "LE_lADOABII586zygLzzwAAAAQMPFMe",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/17385149214",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2025-04-24T07:48:47Z",
      "label": {
        "name": "CI failed",
        "color": "cccccc"
      }
    }
  ]
}