{
  "type": "issue",
  "issue": {
    "id": 3283653977,
    "node_id": "I_kwDOABII587DuJVZ",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/33114",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/33114/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/33114/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/33114/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/33114",
    "number": 33114,
    "state": "open",
    "state_reason": null,
    "title": "intermittent issue in wallet_sendall.py\", line 440, in sendall_anti_fee_sniping                                        assert_greater_than(tx_from_wallet[\"decoded\"][\"locktime\"], tx_from_wallet[\"blockheight\"]",
    "body": "https://github.com/bitcoin/bitcoin/actions/runs/16636698220/job/47078938995#step:7:16110:\n\n```\n test  2025-07-31T01:37:44.029094Z TestFramework (ERROR): Unexpected exception \n                                   Traceback (most recent call last):\n                                     File \"/home/runner/work/bitcoin/bitcoin/test/functional/test_framework/test_framework.py\", line 195, in main\n                                       self.run_test()\n                                     File \"/home/runner/work/bitcoin/bitcoin/build/test/functional/wallet_sendall.py\", line 536, in run_test\n                                       self.sendall_anti_fee_sniping()\n                                     File \"/home/runner/work/bitcoin/bitcoin/build/test/functional/wallet_sendall.py\", line 21, in wrapper\n                                       func(self)\n                                     File \"/home/runner/work/bitcoin/bitcoin/build/test/functional/wallet_sendall.py\", line 440, in sendall_anti_fee_sniping\n                                       assert_greater_than(tx_from_wallet[\"decoded\"][\"locktime\"], tx_from_wallet[\"blockheight\"] - 100)\n                                     File \"/home/runner/work/bitcoin/bitcoin/test/functional/test_framework/util.py\", line 87, in assert_greater_than\n                                       raise AssertionError(\"%s <= %s\" % (str(thing1), str(thing2)))\n                                   AssertionError: 37 <= 37",
    "user": {
      "login": "maflcko",
      "id": 6399679,
      "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/maflcko",
      "html_url": "https://github.com/maflcko",
      "followers_url": "https://api.github.com/users/maflcko/followers",
      "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
      "organizations_url": "https://api.github.com/users/maflcko/orgs",
      "repos_url": "https://api.github.com/users/maflcko/repos",
      "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/maflcko/received_events",
      "type": "User",
      "site_admin": false,
      "patch_url": null
    },
    "labels": [
      {
        "id": 5334691551,
        "node_id": "LA_kwDOABII588AAAABPfju3w",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/CI%20failed",
        "name": "CI failed",
        "description": "",
        "color": "cccccc",
        "default": false
      }
    ],
    "assignees": [],
    "author_association": "MEMBER",
    "locked": false,
    "comments": 0,
    "created_at": "2025-08-01T11:52:45Z",
    "updated_at": "2025-08-01T11:52:56Z"
  },
  "events": [
    {
      "event": "labeled",
      "id": 18938237794,
      "node_id": "LE_lADOABII587DuJVZzwAAAARozpNi",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/18938237794",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2025-08-01T11:52:56Z",
      "label": {
        "name": "CI failed",
        "color": "cccccc"
      }
    }
  ]
}